name: deploy-main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check prisma has changes
        uses: dorny/paths-filter@v3
        id: paths-filter
        with:
          filters: |
            prisma: ["prisma/**"]

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          # Secret 값을 변수 거치지 않고 직접 파일에 씁니다.
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # HostName 뒤에 직접 Secret 값을 꽂아넣습니다.
          cat >> ~/.ssh/config <<EOF
          Host umc9thworkbook
            HostName ${{ secrets.EC2_HOST }}
            User ubuntu
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          EOF

      - name: Copy Workspace
        run: |
          ssh umc9thworkbook 'sudo mkdir -p /opt/app'
          ssh umc9thworkbook 'sudo chown ubuntu:ubuntu /opt/app'
          scp -r ./[!.]* umc9thworkbook:/opt/app

      - name: Install dependencies
        run: |
          ssh umc9thworkbook 'npm install --prefix /opt/app/'
          ssh umc9thworkbook 'cd /opt/app; npx prisma generate'
    
      - name: Apply prisma migrations
        if: steps.paths-filter.outputs.prisma == 'true'
        run: |
          ssh umc9thworkbook 'cd /opt/app; npx prisma migrate deploy'

      - name: Copy systemd service file
        run: |
          ssh umc9thworkbook '
            echo "[Unit]
            Description=UMC 9th Project
            After=network.target

            [Service]
            User=${USER}
            ExecStart=/usr/bin/npm run start --prefix /opt/app/
            Restart=always

            [Install]
            WantedBy=multi-user.target" | sudo tee /etc/systemd/system/app.service
          '

      - name: Enable systemd service
        run: |
          ssh umc9thworkbook 'sudo systemctl daemon-reload'
          ssh umc9thworkbook 'sudo systemctl enable app'

      - name: Restart systemd service
        run: |
          ssh umc9thworkbook 'sudo systemctl restart app'
